name: Code Mistake
description: File an issue with one of the code repositories.
labels: ["code-bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please ensure that the bug has not already been filed in the issue tracker.

        Thanks for taking the time to report this bug!
  - type: dropdown
    attributes:
      label: Section
      description: Which Section is this an issue for?
      multiple: false
      options:
        - Section 1 | Blockchain Basics
        - Other (please describe)
    validations:
      required: true
  - type: input
    attributes:
      label: Could you please leave a link to the Cyfrin Updraft Lesson (or YouTube video timestamp) where this error occurs? (You can right click a video and "copy video URL at current time")
      placeholder: "https://updraft.cyfrin.io/courses/blockchain-basics/basics/welcome-to-updraft"
  - type: dropdown
    attributes:
      label: Operating System
      description: What operating system are you on?
      options:
        - Windows
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux
  - type: textarea
    attributes:
      label: Describe the bug
      description: Please include relevant code snippets as well if relevant. Remember to format!
    validations:
      required: true
